### ISSUE TITLE
Font not bolded 

### ISSUE THREAD

**Issue by ewabuk** [fakespot-app/fakespot#10]
![zrzut ekranu 2018-03-17 o 21 05 58](https://user-images.githubusercontent.com/37385064/37559841-3868bc02-2a2d-11e8-9dc6-2c47a2f2a09f.png)

Some examples have unbolded font in "gdzie dobrze sprawdzać taką informację".

**Comment by bibixx** [comment]
This is due to the fact that fail screen should be made to be more like a success. Because of the planned UI redesign I won't be fixing it
