### ISSUE TITLE
Source link doesn't fit in the source field 

### ISSUE THREAD

**Issue by ewabuk** [fakespot-app/fakespot#11]
![zrzut ekranu 2018-03-17 o 21 51 00](https://user-images.githubusercontent.com/37385064/37559851-57bda9dc-2a2d-11e8-9a4b-8f804e4c3a45.png)

In some examples the source link doesn't fit in the source field

**Comment by ewabuk** [comment]
![zrzut ekranu 2018-03-17 o 21 57 54](https://user-images.githubusercontent.com/37385064/37559919-ab4ea398-2a2e-11e8-80c3-6171212933be.png)

**Comment by bibixx** [comment]
https://github.com/fakespot-app/fakespot/commit/c5620ce57b366f8b2ff78219fdc4e2e68dcb9df5
